### ISSUE TITLE
no server launching

### ISSUE THREAD

**Issue by kaktus42** [calitek/ReactPatterns#2]
I'm trying React.14/ReFluxElectron on Ubuntu

I changed gulpfile.js`from
```
else shellTaskArgument = './node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ./../ReFluxElectron';
```
```
else shellTaskArgument = './node_modules/.bin/electron .';
```

`gulp`
gives

> [18:00:06] Using gulpfile /tmp/ReactPatterns/React.14/ReFluxElectron/gulpfile.js
[18:00:06] Starting 'appjs'...
[18:00:06] Finished 'appjs' after 16 ms
[18:00:06] Starting 'appcss'...
[18:00:06] Finished 'appcss' after 7.07 ms
[18:00:06] Starting 'apphtml'...
[18:00:06] Finished 'apphtml' after 1.96 ms
[18:00:06] Starting 'watch'...
[18:00:06] Finished 'watch' after 14 ms
[18:00:06] Starting 'default'...
[18:00:06] Finished 'default' after 7.16 μs

and `npm start`

> 
> ReactPatterns.14-ReFluxElectron@1.0.0 start /tmp/ReactPatterns/React.14/ReFluxElectron
> gulp
> 
> [18:00:15] Using gulpfile /tmp/ReactPatterns/React.14/ReFluxElectron/gulpfile.js
> [18:00:15] Starting 'appjs'...
> [18:00:15] Finished 'appjs' after 15 ms
> [18:00:15] Starting 'appcss'...
> [18:00:15] Finished 'appcss' after 6.65 ms
> [18:00:15] Starting 'apphtml'...
> [18:00:15] Finished 'apphtml' after 1.22 ms
> [18:00:15] Starting 'watch'...
> [18:00:15] Finished 'watch' after 17 ms
> [18:00:15] Starting 'default'...
> [18:00:15] Finished 'default' after 7.56 μs

But there is no server running.

**Comment by calitek** [comment]
Hi, you should use 'gulp nw' to compile and then 'gulp run' to run.
